[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "proofatlas"
dynamic = [
    "version"
]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]
include = ["proofatlas*"]
namespaces = false
