[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foreduce"
dynamic = [
    "version",
    "dependencies",
    "optional-dependencies"
]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["foreduce*"]
namespaces = false

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}
